# Use an official Nginx image as a parent image
FROM nginx:latest

# Set the working directory in the container to /usr/share/nginx/html
WORKDIR /usr/share/nginx/html

# Copy the static website files into the container at /usr/share/nginx/html
COPY . .